### ISSUE TITLE
New formats are not "pluggable"

### ISSUE THREAD

**Issue by akshaysmurthy** [VasishtaShastry/SARA#1]
While I agree that adding new formats is as easy as adding a line of code, with a language like Python, even that is unnecessary :)

**Comment by VasishtaShastry** [comment]
Thanks for going through my code.
I'll work on it.

**Comment by VasishtaShastry** [comment]
I could make it 'pluggable' using 'pathlib'
but main draw back is 'pathlib' is available in 'python3.4'
Even I had considered using 'os.listdir()'
