### ISSUE TITLE
File names

### ISSUE THREAD

**Issue by akshaysmurthy** [VasishtaShastry/SARA#3]
Generally the convention is to use class names as the name of the file too. Eg., a class `Person` should be in a file called **person.py**

**Comment by VasishtaShastry** [comment]
Okay 
Will follow it  :)

**Comment by akshaysmurthy** [comment]
Any updates on this one?

**Comment by VasishtaShastry** [comment]
Only one - base.py was remaining.
missed it somewhere copying from work space.
now it has been changed :) 
Actually this issue gave me a major clue.
Thanks :)

**Comment by akshaysmurthy** [comment]
:+1:
