### ISSUE TITLE
Console input handled by multiple classes

### ISSUE THREAD

**Issue by akshaysmurthy** [VasishtaShastry/SARA#4]
The `Alien` and `ExportAlienDetails` classes are both handling console input. This is not so good in two ways -
- Unnecessary responsibilities for the two classes
- If you have to change the input method to a file instead of the console, then changes will be required in multiple places

**Comment by VasishtaShastry** [comment]
hmm yes :)
I should have kept it 
Initially I had planned like that
During course of developing somewhere I left it :(

**Comment by VasishtaShastry** [comment]
A new module 'inputHandler' has been added which manages console input
Please checkout

**Comment by akshaysmurthy** [comment]
@VasishtaShastry This is better!
